version: "5.12"
servers:
  - id: default
    # FIXME: try to ensure does not fall back to MX delivery for received messages
    transport: sink
    phases:
      data:
        # Minor performance optimization - see https://docs.halon.io/manual/config_tuning.html?highlight=multipart#servers-phases-data-multipart
        multipart: false
      eod:
        hook: default
    tls:
      certs: 
        cert: h4.espops.com
      protocols: TLSv1.2,TLSv1.3
      ciphers: aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH
transportgroups:
  - id: default
    retry:
      count: 30
      intervals:
        - interval: 60
        - interval: 900
        - interval: 3600
          notify: true
        - interval: 7200
        - interval: 10800
    dsn:
      transport: mx
    transports:
      - id: mx
        session:
          tls:
            mode: optional
      - id: sink
resolver:
  cache:
    size: 10000

# See smtpd.yaml. Note the cert is loaded separately here to permit reloads on cert refresh.
pki:
  private:
  - id: h4.espops.com
    certificate:
      path: /etc/letsencrypt/live/h4.espops.com/fullchain.pem
