version: "5.12"
servers:
  - id: default
    # received messages go to the sink
    transport: sink
    phases:
      data:
        # Minor performance optimization - see https://docs.halon.io/manual/config_tuning.html?highlight=multipart#servers-phases-data-multipart
        multipart: false
      eod:
        hook: sink

  - id: submission
    transport: mx
    phases:
      data:
        # Minor performance optimization - see https://docs.halon.io/manual/config_tuning.html?highlight=multipart#servers-phases-data-multipart
        multipart: false
      eod:
        hook: default

  - id: queue_to_sink
    transport: loopback_to_sink
    phases:
      data:
        # Minor performance optimization - see https://docs.halon.io/manual/config_tuning.html?highlight=multipart#servers-phases-data-multipart
        multipart: false
      eod:
        hook: default

transportgroups:
  - id: default
    retry:
      count: 30
      intervals:
        - interval: 60
        - interval: 900
        - interval: 3600
          notify: true
        - interval: 7200
        - interval: 10800
    # Disable DSNs as we do not want backscatter spam coming back from MTA due to bounces from the sink.
    # dsn:
    #   transport: mx
    transports:
      - id: mx
        session:
          tls:
            mode: optional
        connection:
          sourceip:
            ipv6: false # Disable for now, as AWS EC2 doesn't provide an outbound IPv6 gateway by default

      - id: sink
        # don't deliver onwards

      - id: loopback_to_sink
        # here we use IPv6 internally, just because we can (127.0.0.1 would also work)
        connection:
          port: 2525
          server: ::1
resolver:
  cache:
    size: 10000

queues:
  pooling:
    size: 1000
    policy: remotemx
  grouping:
    default: recipientdomain
    groupings:
      - id: google
        #remotemx:
        #  - "*.google.com"
        #  - "*.googlemail.com"
        #  - "*.smtp.goog"
        recipientdomain:
          - google.com
      - id: microsoft
        recipientdomain:
          - hotmail.com
          - msn.com
          - hotmail.co.jp
          - live.com
          - outlook.com
          - hotmail.co.uk
          - hotmail.fr
          - live.jp
          - hotmail.de
          - live.co.uk
          - hotmail.es
          - live.fr
          - live.in
        #remotemx:
        #  - "*.protection.outlook.com"
      - id: yahoo
        recipientdomain:
          - yahoo.com.br
          - yahoo.com
          - yahoo.co.in
          - yahoo.in
          - yahoo.ca
          - yahoo.co.uk
          - yahoo.es
          - yahoo.de
          - yahoo.it
          - yahoo.gr
          - yahoo.ie
        #remotemx:
        #  - "*.yahoodns.net"
# See smtpd.yaml. Note the cert is loaded separately here to permit reloads on cert refresh.
#pki:
#  private:
#  - id: h4.espops.com
#    certificate:
#      path: /etc/letsencrypt/live/h4.espops.com/fullchain.pem
