version: "5.12"
servers:
  - id: default
    listeners:
      # For localhost only, this is the sink
      - address: 127.0.0.1
        port: 2525
      #- address: ::1
      #  port: 587

  - id: submission
    listeners:
      # For localhost only, queue messages for external delivery
      - address: 127.0.0.1
        port: 587
      #- address: ::1
      #  port: 587

  - id: queue_to_sink
    listeners:
      # External + internal listener. Queue messages through the MTA for loopback to sink
    - port: 25

environment:
  uuid:
    version: 4
  controlsocket:
    group: staff
    chmod: "0660"
  privdrop:
    user: halon
    group: halon
  umask: "0027"
  rlimit:
    nofile: 70000
  syslog:
    # Disable huge logfiles
    # https://docs.halon.io/manual/config_startup.html#confval-environment.syslog.mask
    mask: 191
    
# Use a valid key/cert to offer inbound STARTTLS.
# Note the cert part will be loaded in smtpd-app.yaml to permit reloads on cert refresh.
#pki:
  #private:
  #- id: h4.espops.com
  #  privatekey:
  #    path: /etc/letsencrypt/live/h4.espops.com/privkey.pem
